name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup pip cache
        run: echo "${{ github.workspace }}/.cache/pip" > ${{ github.workspace }}/.cache
      - name: Display Python and pip versions
        run: python --version && pip --version
      - name: Install and run ruff
        run: |
          pip install ruff
          ruff check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup pip cache
        run: echo "${{ github.workspace }}/.cache/pip" > ${{ github.workspace }}/.cache
      - name: Display Python and pip versions
        run: python --version && pip --version
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies and run tests
        run: |
          pip install pytest httpx
          pip install -r requirements.txt
          pytest

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alaboy19/mlops-hm07:n-bazarbek
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   needs: [lint, test, build]
  #   steps:
  #     - name: Deploy to Render
  #       run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}