name: Test, Build, and Deploy

on:
  push:
    branches:
      - main  # Or any specific branch you want to trigger on

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'latest'
          cache: 'pip' 
          cache-dependency-path: requirements.txt

      - name: Install Ruff
        run: pip install ruff

      - name: Run Linter
        run: ruff check

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensure lint job completes successfully first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'latest'
          cache: 'pip' 
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt pytest httpx

      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test  # Ensure test job completes successfully first
    container:
      image: gcr.io/kaniko-project/executor:v1.14.0-debug
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${{ secrets.DOCKERHUB_USERNAME }}" "${{ secrets.DOCKERHUB_TOKEN }}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
          /kaniko/executor --context "${{ github.workspace }}" --dockerfile "${{ github.workspace }}/Dockerfile" --destination "alaboy19/mlops-hm07:n-bazarbek"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Use GitHub Secrets
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Trigger Render deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}